version: "3.9"
services:
  api:
    build:
      context: ./api
    image: my-go-api:1.0   # custom tag for the built image
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7         # official image
